CREATE TABLE IF NOT EXISTS hostels (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  location VARCHAR(200),
  total_rooms INT NOT NULL DEFAULT 0,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS rooms (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  hostel_id BIGINT NOT NULL,
  room_number VARCHAR(20) NOT NULL,
  capacity INT NOT NULL DEFAULT 2,
  current_occupancy INT NOT NULL DEFAULT 0,
  room_gender ENUM('MALE','FEMALE') NOT NULL,
  mattress_type ENUM('NORMAL','QUEEN') NOT NULL DEFAULT 'NORMAL',
  has_ac BOOLEAN NOT NULL DEFAULT FALSE,
  has_wifi BOOLEAN NOT NULL DEFAULT TRUE,
  status ENUM('AVAILABLE','FULL') NOT NULL DEFAULT 'AVAILABLE',
  price DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  floor_number INT NOT NULL DEFAULT 1,
  version BIGINT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_rooms_hostel FOREIGN KEY (hostel_id) REFERENCES hostels(id) ON DELETE CASCADE,
  CONSTRAINT unique_room UNIQUE (hostel_id, room_number)
);

CREATE TABLE IF NOT EXISTS students (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  full_name VARCHAR(120) NOT NULL,
  email VARCHAR(200) NOT NULL,
  phone VARCHAR(30),
  gender ENUM('MALE','FEMALE') NOT NULL,
  password VARCHAR(200) NOT NULL,
  role ENUM('ADMIN','STUDENT') NOT NULL DEFAULT 'STUDENT',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT unique_student_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS bookings (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  student_id BIGINT NOT NULL,
  room_id BIGINT NULL,
  status ENUM('PENDING_PAYMENT','APPROVED','REJECTED','EXPIRED','CANCELLED') NOT NULL,
  special_requests VARCHAR(500),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_bookings_student FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE,
  CONSTRAINT fk_bookings_room FOREIGN KEY (room_id) REFERENCES rooms(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS payments (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  student_id BIGINT NOT NULL,
  booking_id BIGINT NOT NULL,
  amount DECIMAL(10,2) NOT NULL,
  status ENUM('PENDING','COMPLETED','CANCELLED','REFUNDED') NOT NULL,
  due_at TIMESTAMP NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_payments_student FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE,
  CONSTRAINT fk_payments_booking FOREIGN KEY (booking_id) REFERENCES bookings(id) ON DELETE CASCADE,
  CONSTRAINT unique_payment_booking UNIQUE (booking_id)
);

CREATE INDEX idx_rooms_hostel ON rooms(hostel_id);
CREATE INDEX idx_rooms_gender ON rooms(room_gender);
CREATE INDEX idx_rooms_status ON rooms(status);

CREATE INDEX idx_bookings_student ON bookings(student_id);
CREATE INDEX idx_bookings_status ON bookings(status);
CREATE INDEX idx_bookings_student_status ON bookings(student_id, status);

CREATE INDEX idx_payments_status ON payments(status);
